apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps
    repoURL: https://github.com/BernhardDenner/gp-poc.git
    targetRevision: HEAD
    helm:
      parameters:
      - name: "source.gpRepoUrl"
        value: https://github.com/BernhardDenner/gp-poc.git
      values: |
        gpRancherMonitoring:
          profile: small
          customValues: |
            rancher-monitoring:
              prometheus:
                annotations:
                  customvalues: hello

